# This is a basic workflow to help you get started with Actions

name: Pagespeed Insights

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1.3
      id: psi
      with:
        url: "https://strukteon.github.io/3d-dice-animation/"
        threshold: 70
        strategy: mobile
        key: ${{ secrets.PAGESPEED_APIKEY }}
